version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: .
    command: ["api"]
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/tasks?sslmode=disable
      REDIS_ADDR: redis:6379
      HTTP_PORT: "8080"
      APP_ENV: dev
      UPLOADS_DIR: /app/uploads
      STATIC_DIR: /app/web
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
  worker:
    build: .
    command: ["worker"]
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/tasks?sslmode=disable
      REDIS_ADDR: redis:6379
      APP_ENV: dev
      UPLOADS_DIR: /app/uploads
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
  worker-2:
    build: .
    command: ["worker"]
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/tasks?sslmode=disable
      REDIS_ADDR: redis:6379
      APP_ENV: dev
      UPLOADS_DIR: /app/uploads
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
